server:
  port: 8001

spring:
  session:
    #关闭spring-session
    store-type: none
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/auth_center?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    #连接超时时间
    timeout: 5000



#Security 配置
security:
  browser:
    #自定义系统登录页面地址
    #loginPage: /login.html
    loginType: JSON