server:
  port: 80
  servlet:
    session:
      #超时时间，单位：秒 （springboot中最少1分钟，默认 30分钟）
      timeout: 600

spring:
  session:
    #关闭spring-session
    store-type: none

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/auth_center?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    #连接超时时间
    timeout: 5000

#Security 配置
security:
  browser:
    # 自定义系统登录页面地址
    #loginPage: /login.html
    # 系统注册页面
    signUpUrl: /signUp.html
    # 登录类型配置：JSON（默认）  REDIRECT
    loginType: JSON
    # 静态资源放行
    staticResources: /static/**

    session:
      # 同一个用户在系统中的最大session数，默认1
      maximumSessions: 1
      # 达到最大session时是否阻止新的登录请求，默认为false，不阻止，新的登录会将老的登录失效掉
      maxSessionsPreventsLogin: false
      # session失效时跳转的地址
      sessionInvalidUrl: http://www.baidu.com

  # 验证码配置
  code:
    image:
      length: 4
      height: 23
      width: 67
      expireIn: 60
      url: /user/login

  # 三方登录
  social:
    filterProcessesUrl: /auth
    qq:
      appId: 101744435
      appSecret: 15abaee5e181376117ac7020a032fb5e
      providerId: qq
    wechat:
      appId: wxd99431bbff8305a0
      appSecret: 60f78681d063590a469f1b297feff3c4
      providerId: wechat
